#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
