#!/usr/bin/env bash
# Installs, configures, and starts the server

ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
