#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

# ps aux | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP

# Find the Gunicorn master process ID
master_pid=$(ps aux | grep '[g]unicorn' | awk '{print $2}' | head -n 1)

if [ -z "$master_pid" ]; then
    echo "Gunicorn master process not found. Make sure Gunicorn is running."
    exit 1
fi
# Send a HUP signal to the Gunicorn master process
kill -HUP $master_pid
